apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: knative
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: argo-applications
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://github.com/kubeflow/manifests
      path: common/knative/knative-serving/overlays/gateways
      targetRevision: v1.9-branch
      directory:
        recurse: true
    - repoURL: https://github.com/kubeflow/manifests
      path: common/knative/knative-eventing/base
      targetRevision: v1.9-branch
      kustomize:
      directory:
        recurse: true
    - repoURL: https://github.com/kubeflow/manifests
      path: common/istio-1-17/cluster-local-gateway/base
      targetRevision: v1.9-branch
      kustomize:
      directory:
        recurse: true
  project: default
