apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow-pipelines
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: argo-applications
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://github.com/kubeflow/manifests
      path: apps/pipeline/upstream/env/cert-manager/platform-agnostic-multi-user
      targetRevision: v1.9-branch
  project: default
