apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: kubeflow-istio-resource
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: argo-applications
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://github.com/kubeflow/manifests
      path: common/istio-1-17/kubeflow-istio-resources/base
      targetRevision: v1.9-branch
      kustomize:
      directory:
        recurse: true
  project: default
