apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: tensorbard-web-app
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: argo-applications
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://github.com/kubeflow/manifests
      path: apps/tensorboard/tensorboards-web-app/upstream/overlays/istio
      targetRevision: v1.9-branch
      kustomize:
      directory:
        recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
